### ISSUE TITLE
Win32: Java 15 compilation of JRI fails due to `yield` keyword

### ISSUE THREAD

**Issue by ZivanKaraman** [s-u/rJava#241]
Hello,

I'm trying to install rJava from source package rJava_0.9-13.tar.gz (from CRAN) under R 3.6.3 on Windows.

I'm getting the following message:
```R
inferring 'repos = NULL' from 'pkgs'
* installing *source* package 'rJava' ...
** package 'rJava' successfully unpacked and MD5 sums checked
** using staged installation
Generate Windows-specific files (src/jvm-w32) ...
make: Entering directory '/Temp/RtmpgjTSA9/R.INSTALL1b48215e3617/rJava/src/jvm-w32'
c:/Rtools/mingw_64/bin/dlltool --as c:/Rtools/mingw_64/bin/as  --input-def jvm64.def --kill-at --dllname jvm.dll --output-lib libjvm.dll.a
c:/Rtools/mingw_64/bin/gcc  -O2 -c -o findjava.o findjava.c
c:/Rtools/mingw_64/bin/gcc  -s -o findjava.exe findjava.o
make: Leaving directory '/Temp/RtmpgjTSA9/R.INSTALL1b48215e3617/rJava/src/jvm-w32'
Find Java...
  JAVA_HOME=C:/PROGRA~1/Java/JDK-15~1.1
=== Building JRI ===
  JAVA_HOME=C:/PROGRA~1/Java/JDK-15~1.1
  R_HOME=C:/PROGRA~1/R/R-36~1.3
JDK has no javah.exe - using javac -h . instead
Creating Makefiles ...
Configuration done.
make -C src JRI.jar
make[1]: Entering directory '/Temp/RtmpgjTSA9/R.INSTALL1b48215e3617/rJava/jri/src'
C:/PROGRA~1/Java/JDK-15~1.1/bin/javac -h . -d . ../RList.java ../RBool.java ../RVector.java ../RMainLoopCallbacks.java ../RConsoleOutputStream.java ../Mutex.java ../Rengine.java ../REXP.java ../RFactor.java ../package-info.java
..\Rengine.java:120: error: invalid use of a restricted identifier 'yield'
        while (!alive && !died) yield();
                                ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
1 error
make[1]: *** [Makefile.all:41: org/rosuda/JRI/Rengine.class] Error 1
make[1]: Leaving directory '/Temp/RtmpgjTSA9/R.INSTALL1b48215e3617/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'C:/Program Files/R/R-3.6.3/library/rJava'
Warning message:
In install.packages("rJava_0.9-13.tar.gz") :
  installation of package ‘rJava_0.9-13.tar.gz’ had non-zero exit status
```

I get the same message when trying to rJava_0.9-14.tar.gz or rJava_0.9-12.tar.gz (from http://www.rforge.net/rJava/files/).

I also get the equivalent error when installing under R 4.0.3:
```R
inferring 'repos = NULL' from 'pkgs'
* installing *source* package 'rJava' ...
** package 'rJava' successfully unpacked and MD5 sums checked
** using staged installation
Generate Windows-specific files (src/jvm-w32) ...
make: Entering directory '/Temp/Rtmp2l92q5/R.INSTALL404128a2ef3/rJava/src/jvm-w32'
"C:/rtools40/mingw64/bin/"dlltool --as "C:/rtools40/mingw64/bin/"as  --input-def jvm64.def --kill-at --dllname jvm.dll --output-lib libjvm.dll.a
"C:/rtools40/mingw64/bin/"gcc  -O2 -c -o findjava.o findjava.c
"C:/rtools40/mingw64/bin/"gcc  -s -o findjava.exe findjava.o
make: Leaving directory '/Temp/Rtmp2l92q5/R.INSTALL404128a2ef3/rJava/src/jvm-w32'
Find Java...
  JAVA_HOME=C:/PROGRA~1/Java/JDK-15~1.1
=== Building JRI ===
  JAVA_HOME=C:/PROGRA~1/Java/JDK-15~1.1
  R_HOME=C:/PROGRA~1/R/R-40~1.3
JDK has no javah.exe - using javac -h . instead
Creating Makefiles ...
Configuration done.
make -C src JRI.jar
make[1]: Entering directory '/Temp/Rtmp2l92q5/R.INSTALL404128a2ef3/rJava/jri/src'
C:/PROGRA~1/Java/JDK-15~1.1/bin/javac -h . -d . ../RList.java ../RBool.java ../RVector.java ../RMainLoopCallbacks.java ../RConsoleOutputStream.java ../Mutex.java ../Rengine.java ../REXP.java ../RFactor.java ../package-info.java
..\Rengine.java:120: error: invalid use of a restricted identifier 'yield'
        while (!alive && !died) yield();
                                ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
1 error
make[1]: *** [Makefile.all:41: org/rosuda/JRI/Rengine.class] Error 1
make[1]: Leaving directory '/Temp/Rtmp2l92q5/R.INSTALL404128a2ef3/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'C:/Program Files/R/R-4.0.3/library/rJava'
Warning message:
In install.packages("rJava_0.9-13.tar.gz", lib = "C:/Program Files/R/R-4.0.3/library") :
  installation of package ‘rJava_0.9-13.tar.gz’ had non-zero exit status
```

Additional information:

**R version**
```bash
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock    
```

**OS version**
```bash
Windows 10 x64 (build 17763)
```

**JDK version (release file)**
```bash
IMPLEMENTOR="Oracle Corporation"
JAVA_VERSION="15.0.1"
JAVA_VERSION_DATE="2020-10-20"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.vm.ci jdk.management jdk.unsupported jdk.internal.vm.compiler jdk.aot jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.crypto.mscapi jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.incubator.foreign jdk.internal.opt jdk.jdeps jdk.jlink jdk.incubator.jpackage jdk.internal.le jdk.internal.vm.compiler.management jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom jdk.zipfs"
OS_ARCH="x86_64"
OS_NAME="Windows"
SOURCE=".:hg:841b8fb61b31 open:hg:d9b7c0759310"
```

Any idea what's wrong?

Thanks in advance for your help.

Best regards,
Zivan Karaman

**Comment by s-u** [comment]
JRI should probably set `-source 1.6` or similar to avoid issues introduced in Java 15

**Comment by s-u** [comment]
Ok, this is Windows-only, all other systems already set `-target 1.8 -source 1.8`

**Comment by s-u** [comment]
Ok, this is Windows-only, all other systems already set `-target 1.8 -source 1.8`

**Comment by s-u** [comment]
Please check the latest `rJava 0.9-14` to see if it addresses the issue. (BTW: as the output says, you can always set `IGNORE=1` to install rJava without JRI support).

**Comment by ZivanKaraman** [comment]
It works with the latest ```rJava 0.9-14```.
Thank you very much for your help.

**Comment by delphinehelle** [comment]
Hello, thank you for the lead.
I have the same issue with my JDK11 (similar setup for R).
Do you have any idea to fix this ?

```
Rcallbacks.o:Rcallbacks.c:(.text+0x42): undefined reference to `JNI_GetCreatedJavaVMs'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile.all:35: jri.dll] Error 1
make[1]: Leaving directory '/cygdrive/xxxx/xxxxx/Temp/RtmpO0sDlC/R.INSTALL3c5067415ea4/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
```
It's to built a package hat why I can manage set IGNORE= 1 for his install.

Thanks a lot

**Comment by s-u** [comment]
Thanks!
