### ISSUE TITLE
rJava 0.9-9 fail to work in OS 10.12.5 + R 3.4.1 + JDK  1.8.0_131

### ISSUE THREAD

**Issue by Camilochiang** [s-u/rJava#112]
Hi. I have been working around an small issue with rJava in the mentioned version that summarise in the following:

**Problem:** 
Error in .jnew("Helloworldapp") : 
  java.lang.NoClassDefFoundError: Helloworldapp (wrong name: helloworldapp/Helloworldapp)

Were I'm sure that the the folder helloworldapp exist, that the Class file is in the path and that the variable is Helloworldapp. More basics commands work well (i.e, .jinit, jnew("java/lang/String", "Hello World!"), .jcall)

**Source:**
I was not able to install rJava from R console until I create a symlink (more details below)
`  sudo ln -f -s $(/usr/libexec/java_home)/jre/lib/server/libjvm.dylib /usr/local/lib `

Ones that I did that I'm able to charge it from the console but if I try to do it from Terminal I get the following error, after several warnings:

```
ld: library not found for -lomp
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libjri.jnilib] Error 1
make[1]: *** [src/JRI.jar] Error 2
make: *** [jri] Error 2
ERROR: compilation failed for package ‘rJava’
```

**Software**
I have installed 
Matching Java Virtual Machines (3):
1.8.0_131, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

and gfortran 6.1 and  gfortran-4.2.3.pkg  from
https://gcc.gnu.org/wiki/GFortranBinaries#MacOS-11
https://cran.r-project.org/bin/macosx/tools/

respectively 

my input from R CMD javareconf
```
Java interpreter : /usr/bin/java
Java version     : 1.8.0_131
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
Non-system Java on macOS

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
/usr/local/clang4/bin/clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/../include/darwin  -I/usr/local/include   -fPIC  -Wall -g -O2  -c conftest.c -o conftest.o
/usr/local/clang4/bin/clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/clang4/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.
```

My statements in ~/.R/Makevars

```
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib
```

And I have included the following in the config.h File from R (in R.frameworks/version/3.4/PrivateHeadrs, Just below #define SUPPORT_OPENMP 1):

#include <omp.h>

Any ideas of what could be the source of the problem? You can follow my journal here

https://stackoverflow.com/questions/45051275/rjava-loading-in-r3-4-1-with-os-sierra

Thanks in advance!

**Comment by muschellij2** [comment]
See https://cran.r-project.org/bin/macosx/tools/ for clang that is suggested, which supports openmp.  It seems that few similar issues had come up (https://github.com/jonclayden/mmand/issues/4), and some solutions were present in that package when `configure` and `configure.ac` were changed: https://github.com/jonclayden/mmand

Here is a detailed discussion of the problem for `-fopenmp`
http://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/

I will say, though, that this flag may be passed through the linker and not the configuration part of the script:

```
ccache clang -o libjri.jnilib Rengine.o jri.o Rcallbacks.o Rinit.o globals.o rjava.o  -dynamiclib -framework JavaVM -fopenmp -L/usr/local/lib -F/Library/Frameworks/R.framework/.. -framework R -lpcre -llzma -lbz2 -lz -licucore -lm -liconv
```

**Comment by s-u** [comment]
Please read Java docs - you have to use fully qualified names in classes with `.jnew()`.

**Comment by muschellij2** [comment]
This solves that problem for the `.jnew()`, but compiling rJava from source still fails on OS X Sierra because of clang and OpenMP problem:

```
install.packages("rJava", type = "source", repos = "https://cloud.r-project.org")
```
...
```
ccache clang -o libjri.jnilib Rengine.o jri.o Rcallbacks.o Rinit.o globals.o rjava.o  -dynamiclib -framework JavaVM -fopenmp -L/usr/local/lib -F/Library/Frameworks/R.framework/.. -framework R -lpcre -llzma -lbz2 -lz -licucore -lm -liconv
clang: error: unsupported option '-fopenmp'
make[2]: *** [libjri.jnilib] Error 1
make[1]: *** [src/JRI.jar] Error 2
make: *** [jri] Error 2
ERROR: compilation failed for package ‘rJava’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava’
```

```
R CMD javareconf
Java interpreter : /usr/bin/java
Java version     : 1.8.0_91
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
Non-system Java on macOS

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
ccache clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/../include/darwin  -I/usr/local/include   -fPIC  -Wall -g -O2  -c conftest.c -o conftest.o
ccache clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.
```

But it should work with CRAN-recommended `clang` and other tools.

**Comment by s-u** [comment]
It does - please see R docs: R 3.4.0 requires clang4 - it doesn't work with old clang in Apple's Xcode.
